version: 2
jobs:
  test:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-stretch
      - image: circleci/mysql:8.0.20
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: 'root'
          MYSQL_DATABASE: React_API
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''

    working_directory: ~/Laravel.React
      steps:
          - checkout
            - run:
            name: Update apt-get
            command: sudo apt-get update
              - run:
                  name: Docker php extensions install
                  command: sudo docker-php-ext-install pdo_mysql
              - restore_cache:
                  keys:
                    - v1-dependencies-{{ checksum "composer.json" }}
                    - v1-dependencies-
              - run:
                  name: Install PHP libraries
                  command: composer install -n --prefer-dist
              - save_cache:
                  paths:
                    - ./vendor
                  key: v1-dependencies-{{ checksum "composer.json" }}
              - run:
                  name: Run PHPUnit
                  command: vendor/bin/phpunit