
version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.2-stretch
      - image: circleci/mysql:8.0.20
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_USER: 'root'
          MYSQL_DATABASE: 'React_API'
          MYSQL_ROOT_PASSWORD: ' '
          MYSQL_PASSWORD: ' '

    working_directory: ~/Laravel.React
    steps:
      - checkout
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "Laravel.React/composer.json" }}
            - composer-v1-
      - run:
            working_directory: Laravel.React
            command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "Laravel.React/composer.json" }}
          paths:
            - vendor
      - run:
          working_directory: Laravel.React
          name: Run PHPUnit
          command: vendor/bin/phpunit

workflows:
  version: 2
  workflow:
    jobs:
      - test
