version: 1
update_configs:
  - package-ecosystem: "composer"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "increase_versions"